### ISSUE TITLE
Seems to be broken as of today

### ISSUE THREAD

**Issue by eliblanco87** [wewman/gelbash#1]
It always says: "Done, no more files" and downloads 0 files

**Comment by wewman** [comment]
Sorry about the late reply, I have been busy with school. I will do some testing and update it. It's probably a temporary URL Gelbooru rotates every now and then though.

**Comment by wewman** [comment]
Tested the current code in the repo, it works fine today. I have to know what other URLs gelbooru uses, but I will probably improve it later on. Try it now, it should work fine.

What tags were you using? How were you using it?

Thank you for the info!

**Comment by eliblanco87** [comment]
It works now, thanks!
